from typing import Protocol


class DataStore(Protocol):
    def get_firmalar(self) -> list[dict]: ...

    def save_firmalar(self, firmalar: list[dict]) -> None: ...

    def get_ayarlar(self) -> dict: ...

    def save_ayarlar(self, ayarlar: dict) -> None: ...

    def get_kullanicilar(self) -> list[dict]: ...

    def save_kullanicilar(self, kullanicilar: list[dict]) -> None: ...

    def get_adjust_hareketler(self) -> list[dict]: ...

    def upsert_adjust_hareketler(self, hareketler: list[dict]) -> None: ...
